### ISSUE TITLE
Bug preventing scene loading in 9.X

### ISSUE THREAD

**Issue by marcottedan** [dev7355608/perfect-vision#167]
I think I finally narrowed the bug down to Perfect Vision. 

**Versions**
* Latest Foundry 9.X
* All modules up-to-date as of 5 minutes ago
* Latest 5e System

**Setup**
* Scene A: Inn with tokens on it, walls, lights, parallax tile, one Patrol Path
* Scene B: World Map (mostly empty and RAW foundry stuff) with a Snow Weather effect

**Bug**
When I move from Scene B to Scene A, I get the following stack traces (see below).
However if I open Scene A first (scene is Active and I do a refresh in the browser) I'm ok.

If I disable Perfect Vision, everything works #1 and I can switch scenes anywhere.

**Plugin List**
![image](https://user-images.githubusercontent.com/2078143/147369422-0092c503-7f60-4f5f-8858-49a357f41eb1.png)
![image](https://user-images.githubusercontent.com/2078143/147369425-f3a5cb2c-be32-4f2d-a7e2-3fb4b2da4339.png)
![image](https://user-images.githubusercontent.com/2078143/147369428-9dff2867-04f0-4e16-930a-65e98d2804f6.png)

**Stack Trace**
![image](https://user-images.githubusercontent.com/2078143/147369369-2fba9b27-4f58-4ce1-9e99-2e2278e301f6.png)

**Comment by marcottedan** [comment]
Could be related or not:

Once the scene is broken and I switch back to my World Map (with a normal weather effect) I get this: 

![image](https://user-images.githubusercontent.com/2078143/147369717-95b368f6-0719-4dec-b254-884b5c94bb3a.png)

**Comment by dev7355608** [comment]
Fixed in 3.2.3.

**Comment by marcottedan** [comment]
Thanks!

I just updated but I still have the following bug: 

![image](https://user-images.githubusercontent.com/2078143/147390998-9e6a27d1-db95-416f-9097-cd4fff4b8c71.png)

**Comment by marcottedan** [comment]
I can create you a character on my foundry server if you want to debug there btw.

**Comment by dev7355608** [comment]
Please double check that PV is up to date, and CTRL+F5 to fix any potential cache problems.

**Comment by marcottedan** [comment]
I wiped my cache, upgraded PV to 3.2.4

Repro steps: 

Load first scene named "Hall" which is a background with a basic Weather.

Switch to my "Inn" scene and get this:

![image](https://user-images.githubusercontent.com/2078143/147392033-80d34354-8dc8-4c66-a15b-dd656c991042.png)

**Comment by dev7355608** [comment]
Fixed it really this time, I hope.

**Comment by marcottedan** [comment]
\[T]/

Good job it works!
