### ISSUE TITLE
Tokens in heavily obscured areas remain visible

### ISSUE THREAD

**Issue by YugoNumachi** [dev7355608/perfect-vision#71]
It seems that when Perfect Vision is enabled, tokens which are in heavily obscured areas (having Unrestricted Vision Range being disabled due to darkness threshold) remain visible for the players, while without the module, they disappear if they are out or range for dim vision.

**Comment by dev7355608** [comment]
Fixed in v1.8.9.

**Comment by YugoNumachi** [comment]
Sorry but it's still the same.
If works in the beginning, then if you change the darkness to 0, then back to 1, the tokens are visible outside of range again.
Could be linked to a bug in 0.8.2, as darkness behaves erratically on my system though (i.e. putting it to 0 displays like if it is 0.5).

**Comment by dev7355608** [comment]
It seems to be a bug in Foundry 0.8.2. Even without Perfect Vision lighting and sight are not updated properly when the Vision Limitation Threshold is crossed until the token is moved.

**Comment by dev7355608** [comment]
It's now working with Perfect Vision v1.8.10; at least in Foundry 0.8.3 it should be.
